#define DIRECT_CALL_TRAMPOLINE_SIZE 10
#define DYN_CALL_TRAMPOLINE_SIZE 10

#ifndef NDEBUG
    #define READER_SLOTS_SIZE 0x18
#else
    #define READER_SLOTS_SIZE 0x8
#endif

#define FUH_SLOT_OFFSET 0x8
#define ECTYPE_REG_SAVED_SLOT_OFFSET (FUH_SLOT_OFFSET + 0x8)
#define LITERALS_REG_SAVED_SLOT_OFFSET (ECTYPE_REG_SAVED_SLOT_OFFSET + 0x8)
#define EXTRA_SAVED_REG_OFFSET (LITERALS_REG_SAVED_SLOT_OFFSET + 0x8)
#define READER_SLOT_OFFSET (EXTRA_SAVED_REG_OFFSET + READER_SLOTS_SIZE)
#define LOCAL_SLOTS_OFFSET ((READER_SLOT_OFFSET + 0xf) & ~0xf)

#define TAIL_REG IR7
#define TAIL_REG_OFFS (ECTYPE_IREGS_OFFSET + ECTYPE_REG_SIZE * 7)

#define TLS_REG r15
#define ECTYPE_REG rbx

#define LITERALS_REG r14
#define IREG_ABI_AMOUNT 6
#define FREG_ABI_AMOUNT 8

#define EXTRA_REG r13
#define EXTRA_REGd r13d
