set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_OSX_SYSROOT iphonesimulator CACHE STRING "iOS Simulator SDK")
set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "iOS Simulator architectures")
set(CMAKE_OSX_DEPLOYMENT_TARGET 13.0 CACHE STRING "Minimum iOS version")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
