#if defined(__x86_64__) || defined(_M_X64)
    #include "arch_os/x86_64_linux/platform_asm_export.h"
#elif defined(__aarch64__) || defined(_M_ARM64)
    #include "arch_os/aarch64_linux/platform_asm_export.h"
#endif

#define TRAMPOLINE_COUNT 1024

#define TLS_FIBER_DATA_OFFSET 16
#define FIBER_DATA_ECTYPE_OFFSET 16

#define ECTYPE_IACC_NUM 14
#define ECTYPE_REG_SIZE 8
#define ECTYPE_IREGS_COUNT 15
#define ECTYPE_IREGS_OFFSET 0
#define ECTYPE_FREGS_OFFSET 120
#define ECTYPE_IACC_OFFSET (ECTYPE_IREGS_OFFSET + ECTYPE_REG_SIZE * ECTYPE_IACC_NUM)

#define FUNCTION_HANDLE_C2CALL_OFFSET 8
#define FUNCTION_HANDLE_BYTECODE_OFFSET 16

#define EXEC_BYTECODE_INFO_BYTECODE_SIZE_OFFSET 0
#define EXEC_BYTECODE_INFO_BYTECODE_OFFSET 8
#define EXEC_BYTECODE_INFO_LITERALS_OFFSET 16
#define EXEC_BYTECODE_INFO_SAVED_IREGS_OFFSET 24
#define EXEC_BYTECODE_INFO_SAVED_FREGS_OFFSET 26
#define EXEC_BYTECODE_INFO_FRAME_SIZE_OFFSET 32
#define TYPEINFO_INSTANCESIZE_OFFSET 12

#define TYPEINFO_DATA_MT_OFFSET 96
