#include "arch_os/x86_64_linux/platform_asm_export.h"

#define TRAMPOLINE_COUNT 1024

#define TLS_FIBER_DATA_OFFSET 16
#define FIBER_DATA_ECTYPE_OFFSET 16

#define ECTYPE_IREGS_OFFSET 0
#define ECTYPE_FREGS_OFFSET 128

#define FUNCTION_HANDLE_C2CALL_OFFSET 8
