#define DIRECT_CALL_TRAMPOLINE_SIZE 8
#define DYN_CALL_TRAMPOLINE_SIZE 8

#define FUH_SLOT_OFFSET 0x8

#define LOCAL_SLOTS_OFFSET 0x18

#define TLS_REG x28
#define ECTYPE_REG x19
#define LITERALS_REG x20
#define IREG_ABI_AMOUNT 9
#define FREG_ABI_AMOUNT 8

#ifndef NDEBUG
    #define READER_SLOTS_SIZE 0x18
#else
    #define READER_SLOTS_SIZE 0x8
#endif
